# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Wayland bites
description: >- # this means to ignore newlines until "baseurl:"
  The coverage of the possibilities of the X.Org ecosystem by Wayland compositors
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wayland-bites

# Build settings
theme: minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

xorgfeats:
  - group: ICCCM
    feats:
      - name: WM_STATE
        usage: taskbars, docks, wmctrl, xdotool, etc.
        wlr: wlr-foreign-toplevel-management^1
  - group: EWMH (NetWM)
    feats:
      - name: _NET_SUPPORTED
      - name: _NET_CLIENT_LIST
        usage: wmctrl, rofi, devilspie, xwinmosaic, taskbars, docks, etc.
        wlr: wlr-foreign-toplevel-management^1
      - name: _NET_CLIENT_LIST_STACKING
      - name: _NET_NUMBER_OF_DESKTOPS
      - name: _NET_DESKTOP_GEOMETRY
      - name: _NET_DESKTOP_VIEWPORT
      - name: _NET_CURRENT_DESKTOP
      - name: _NET_DESKTOP_NAMES
      - name: _NET_ACTIVE_WINDOW
      - name: _NET_WORKAREA
      - name: _NET_SUPPORTING_WM_CHECK
      - name: _NET_VIRTUAL_ROOTS
      - name: _NET_DESKTOP_LAYOUT
      - name: _NET_SHOWING_DESKTOP
      - name: _NET_CLOSE_WINDOW
      - name: _NET_MOVERESIZE_WINDOW
        wlr: wlr-foreign-toplevel-management^1
      - name: _NET_WM_MOVERESIZE
      - name: _NET_RESTACK_WINDOW
      - name: _NET_REQUEST_FRAME_EXTENTS
      - name: _NET_WM_NAME
        usage: time trackers, global menus, rofi, xwinmosaic, etc.
        wlr: wlr-foreign-toplevel-management^1
      - name: _NET_WM_VISIBLE_NAME
        wlr: wlr-foreign-toplevel-management^1
      - name: _NET_WM_ICON_NAME
      - name: _NET_WM_VISIBLE_ICON_NAME
      - name: _NET_WM_DESKTOP
      - name: _NET_WM_WINDOW_TYPE
      - name: _NET_WM_STATE
        usage: taskbars, docks, wmctrl, xdotool, etc.
        wlr: wlr-foreign-toplevel-management^1
      - name: _NET_WM_ALLOWED_ACTIONS
      - name: _NET_WM_STRUT
      - name: _NET_WM_STRUT_PARTIAL
      - name: _NET_WM_ICON_GEOMETRY
      - name: _NET_WM_ICON
        usage: global menus, xwinmosaic, etc.
      - name: _NET_WM_PID
      - name: _NET_WM_HANDLED_ICONS
      - name: _NET_WM_USER_TIME
      - name: _NET_WM_USER_TIME_WINDOW
      - name: _NET_FRAME_EXTENTS
      - name: _NET_WM_PING
      - name: _NET_WM_SYNC_REQUEST
      - name: _NET_WM_SYNC_REQUEST_COUNTER
      - name: _NET_WM_FULLSCREEN_MONITORS
      - name: _NET_WM_FULL_PLACEMENT
      - name: _NET_WM_WINDOW_TYPE_DESKTOP
      - name: _NET_WM_WINDOW_TYPE_DOCK
      - name: _NET_WM_WINDOW_TYPE_TOOLBAR
      - name: _NET_WM_WINDOW_TYPE_MENU
      - name: _NET_WM_WINDOW_TYPE_UTILITY
      - name: _NET_WM_WINDOW_TYPE_SPLASH
      - name: _NET_WM_WINDOW_TYPE_DIALOG
      - name: _NET_WM_WINDOW_TYPE_DROPDOWN_MENU
      - name: _NET_WM_WINDOW_TYPE_POPUP_MENU
      - name: _NET_WM_WINDOW_TYPE_TOOLTIP
      - name: _NET_WM_WINDOW_TYPE_NOTIFICATION
      - name: _NET_WM_WINDOW_TYPE_COMBO
      - name: _NET_WM_WINDOW_TYPE_DND
      - name: _NET_WM_WINDOW_TYPE_NORMAL
      - name: _NET_WM_STATE_MODAL
      - name: _NET_WM_STATE_STICKY
      - name: _NET_WM_STATE_MAXIMIZED_VERT
      - name: _NET_WM_STATE_MAXIMIZED_HORZ
      - name: _NET_WM_STATE_SHADED
      - name: _NET_WM_STATE_SKIP_TASKBAR
      - name: _NET_WM_STATE_SKIP_PAGER
      - name: _NET_WM_STATE_HIDDEN
      - name: _NET_WM_STATE_FULLSCREEN
      - name: _NET_WM_STATE_ABOVE
      - name: _NET_WM_STATE_BELOW
      - name: _NET_WM_STATE_DEMANDS_ATTENTION
      - name: _NET_WM_ACTION_MOVE
      - name: _NET_WM_ACTION_RESIZE
      - name: _NET_WM_ACTION_MINIMIZE
      - name: _NET_WM_ACTION_SHADE
      - name: _NET_WM_ACTION_STICK
      - name: _NET_WM_ACTION_MAXIMIZE_HORZ
        wlr: wlr-foreign-toplevel-management^3
      - name: _NET_WM_ACTION_MAXIMIZE_VERT
        wlr: wlr-foreign-toplevel-management^3
      - name: _NET_WM_ACTION_FULLSCREEN
        wlr: wlr-foreign-toplevel-management^1
      - name: _NET_WM_ACTION_CHANGE_DESKTOP
      - name: _NET_WM_ACTION_CLOSE
        wlr: wlr-foreign-toplevel-management^1
      - name: _NET_WM_ACTION_ABOVE
      - name: _NET_WM_ACTION_BELOW
  - group: XKB
    feats:
      - name: XkbLockGroup
        mutter: "?"
        kws: "?"
        wlr: "?"
        mir: "?"
        e: "?"
  - group: Selections
    feats:
    - name: PRIMARY
    - name: SECONDARY
    - name: CLIPBOARD
    - name: ConvertSelection
    - name: Managers
      wlr: wlr-data-control
  - group: XF86VIDMODE
    feats:
    - name: ModeLine
    - name: Gamma
      usage: xbrightness, xgamma, redshift
      wlr: wlr-gamma-control
  - group: Miscellanous
    feats:
    - name: WM crash persistence
      mutter: "-"
      e: Session Recovery Extension^2
    - name: WM decorations
      mutter: "-"
      kws: server-decoration
      wlr: server-decoration
    - name: XShm (screen capture)
      mutter: PipeWire, portals
      wlr: wlr-export-dmabuf

footnotes:
  - Supports only one client at time. Wanna a compositor-independent taskbar and something like Devilspie simultaneously? fail. # 1
  - Requires client support. # 2
  - Can't separately maximize horizontally or vertically. # 3
