# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Wayland bites
description: >- # this means to ignore newlines until "baseurl:"
  The coverage of the possibilities of the X.Org ecosystem by Wayland compositors
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wayland-bites

# Build settings
theme: minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

xorgfeats:
  - group: ICCCM
    feats:
      - name: WM_STATE
        usage: taskbars, docks, wmctrl, xdotool, etc.
        mutter: xdg-shell^5
        kws: xdg-shell / KDE plasma-window-management^1^5
        wlr: xdg-shell / wlr-foreign-toplevel-management^1^5
        mir: xdg-shell^5
        e: xdg-shell^5
  - group: EWMH (NetWM)
    feats:
      - name: _NET_SUPPORTED
      - name: _NET_CLIENT_LIST
        usage: wmctrl, rofi, devilspie, xwinmosaic, taskbars, docks, etc.
        wlr: wlr-foreign-toplevel-management^1
        kws: KDE plasma-window-management^1
        sway: GET_TREE
        mutter: /org/gnome/shell/Introspect / WorkspaceManager.get_workspace_by_index & Workspace.list_windows^17
        e: org.enlightenment.wm.Window.List
      - name: _NET_CLIENT_LIST_STACKING
      - name: _NET_NUMBER_OF_DESKTOPS
        sway: GET_WORKSPACES
        e: org.enlightenment.wm.Desktop.GetVirtualCount
        mutter: WorkspaceManager.get_n_workspaces
      - name: _NET_DESKTOP_GEOMETRY
        sway: GET_WORKSPACES^22
      - name: _NET_DESKTOP_VIEWPORT
        sway: GET_WORKSPACES^22
        mutter: Workspace.get_display^22
      - name: _NET_CURRENT_DESKTOP
        sway: GET_WORKSPACES / workspace
        e: org.enlightenment.wm.Desktop.Show
        mutter: WorkspaceManager.get_active_workspace_index / Workspace.activate
      - name: _NET_DESKTOP_NAMES
        sway: GET_WORKSPACES
        mutter: WorkspaceManager.get_workspace_by_index
      - name: _NET_ACTIVE_WINDOW
        usage: time trackers
        sway: GET_TREE / focus
        mutter: /org/gnome/shell/Introspect / Window.has_focus / Window.focus^17
        e: org.enlightenment.wm.Window.Uniconify^23
      - name: _NET_WORKAREA
        sway: GET_WORKSPACES
        mutter: Window.get_work_area_*
      - name: _NET_SUPPORTING_WM_CHECK
      - name: _NET_VIRTUAL_ROOTS
      - name: _NET_DESKTOP_LAYOUT
        mutter: WorkspaceManager.override_workspace_layout
      - name: _NET_SHOWING_DESKTOP
        mutter: WorkspaceManager.showing-desktop-changed^22
      - name: _NET_CLOSE_WINDOW
        sway: kill^16
        e: org.enlightenment.wm.Window.Close
        mutter: Window.kill
      - name: _NET_MOVERESIZE_WINDOW
        usage: panels, fixed-size windows, popups, Win32 apps
        mutter: xdg-shell / Window.move_resize_frame^5^6
        kws: xdg-shell / KDE plasma-shell ^5^6^11
        wlr: xdg-shell / wlr-foreign-toplevel-management / wlr-layer-shell ^1^5^6
        mir: xdg-shell^5^6
        e: xdg-shell^5^6
      - name: _NET_WM_MOVERESIZE
        mutter: xdg-shell^5
        kws: xdg-shell^5
        wlr: xdg-shell^5
        mir: xdg-shell^5
        e: xdg-shell^5
      - name: _NET_RESTACK_WINDOW
      - name: _NET_REQUEST_FRAME_EXTENTS
        sway: GET_TREE
      - name: _NET_WM_NAME
        usage: time trackers, global menus, rofi, xwinmosaic, etc.
        mutter: xdg-shell / Window.get_title^5
        kws: xdg-shell / KDE plasma-window-management^1^5
        wlr: xdg-shell / wlr-foreign-toplevel-management^1^5
        mir: xdg-shell^5
        e: xdg-shell^5
      - name: _NET_WM_VISIBLE_NAME
        mutter: xdg-shell / Window.get_title^5
        kws: xdg-shell^5
        wlr: xdg-shell / wlr-foreign-toplevel-management^1^5
        mir: xdg-shell^5
        e: xdg-shell^5
      - name: _NET_WM_ICON_NAME
      - name: _NET_WM_VISIBLE_ICON_NAME
      - name: _NET_WM_DESKTOP
        mutter: Window.get_workspace
      - name: _NET_WM_WINDOW_TYPE
      - name: _NET_WM_STATE
        usage: taskbars, docks, wmctrl, xdotool, etc.
        mutter: xdg-shell^5
        kws: xdg-shell^5
        wlr: xdg-shell / wlr-foreign-toplevel-management^1^5
        mir: xdg-shell^5
        e: xdg-shell^5
      - name: _NET_WM_ALLOWED_ACTIONS
        mutter: Window.can_* / Window.allow_*^25
      - name: _NET_WM_STRUT
        usage: panels, docks
        wlr: wlr-layer-shell^5
      - name: _NET_WM_STRUT_PARTIAL
        usage: panels, docks
        wlr: wlr-layer-shell^5
      - name: _NET_WM_ICON_GEOMETRY
        mutter: Window.get_icon_geometry / Window.set_icon_geometry
      - name: _NET_WM_ICON
        usage: global menus, xwinmosaic, etc.
        kws: KDE plasma-window-management^1
      - name: _NET_WM_PID
        kws: KDE plasma-window-management^1
        sway: GET_TREE
        mutter: Window.get_pid
      - name: _NET_WM_HANDLED_ICONS
      - name: _NET_WM_USER_TIME
        mutter: IdleMonitor / Window.get_user_time^24
      - name: _NET_WM_USER_TIME_WINDOW
      - name: _NET_FRAME_EXTENTS
        mutter: Window.get_buffer_rect / Window.get_frame_rect
      - name: _NET_WM_PING
        mutter: xdg-shell
        kws: xdg-shell
        wlr: xdg-shell
        mir: xdg-shell
        e: xdg-shell
      - name: _NET_WM_SYNC_REQUEST
      - name: _NET_WM_SYNC_REQUEST_COUNTER
      - name: _NET_WM_FULLSCREEN_MONITORS
      - name: _NET_WM_FULL_PLACEMENT
      - name: _NET_WM_WINDOW_TYPE_DESKTOP
      - name: _NET_WM_WINDOW_TYPE_DOCK
      - name: _NET_WM_WINDOW_TYPE_TOOLBAR
      - name: _NET_WM_WINDOW_TYPE_MENU
        mutter: Window.get_frame_type
      - name: _NET_WM_WINDOW_TYPE_UTILITY
        mutter: Window.get_frame_type
      - name: _NET_WM_WINDOW_TYPE_SPLASH
      - name: _NET_WM_WINDOW_TYPE_DIALOG
        mutter: Window.get_frame_type
      - name: _NET_WM_WINDOW_TYPE_DROPDOWN_MENU
      - name: _NET_WM_WINDOW_TYPE_POPUP_MENU
      - name: _NET_WM_WINDOW_TYPE_TOOLTIP
      - name: _NET_WM_WINDOW_TYPE_NOTIFICATION
      - name: _NET_WM_WINDOW_TYPE_COMBO
      - name: _NET_WM_WINDOW_TYPE_DND
      - name: _NET_WM_WINDOW_TYPE_NORMAL
        mutter: Window.get_frame_type
      - name: _NET_WM_STATE_MODAL
        mutter: xdg-shell / Window.get_frame_type^5
        kws: xdg-shell^5
        wlr: xdg-shell / wlr-layer-shell ^5
        mir: xdg-shell^5
        e: xdg-shell^5
      - name: _NET_WM_STATE_FOCUSED
        e: org.enlightenment.wm.Window.Focus^23
      - name: _NET_WM_STATE_STICKY
        kws: KDE plasma-window-management^1
        sway: GET_TREE
        mutter: Window.is_always_on_all_workspaces
      - name: _NET_WM_STATE_MAXIMIZED_VERT
        mutter: Window.get_maximized
      - name: _NET_WM_STATE_MAXIMIZED_HORZ
        mutter: Window.get_maximized
      - name: _NET_WM_STATE_SHADED
        kws: KDE plasma-window-management^1
        mutter: Window.is_shaded
      - name: _NET_WM_STATE_SKIP_TASKBAR
        usage: taskbars themselves, and other shell elements
        kws: KDE plasma-shell / KDE plasma-window-management^1^11
        mutter: Window.is_skip_taskbar
      - name: _NET_WM_STATE_SKIP_PAGER
        usage: taskbars, and other shell elements
        kws: KDE plasma-shell / KDE plasma-window-management^1^11
      - name: _NET_WM_STATE_HIDDEN
        mutter: /org/gnome/shell/Introspect / Window.is_hidden^17
      - name: _NET_WM_STATE_FULLSCREEN
        mutter: Window.is_fullscreen
      - name: _NET_WM_STATE_ABOVE
        mutter: Window.is_above
      - name: _NET_WM_STATE_BELOW
      - name: _NET_WM_STATE_DEMANDS_ATTENTION
        usage: IMs, terminal emulators, etc.
        mutter: xdg-activation / Window.demands_attention / Window.set_demands_attention^9
        kws: xdg-activation / KDE plasma-window-management^1^9
        wlr: xdg-activation^9
      - name: _NET_WM_ACTION_MOVE
        sway: move
        mutter: Window.move_frame
      - name: _NET_WM_ACTION_RESIZE
        sway: resize
        mutter: Window.move_resize_frame
      - name: _NET_WM_ACTION_MINIMIZE
        e: org.enlightenment.wm.Window.Iconify
        mutter: Window.minimize
      - name: _NET_WM_ACTION_SHADE
        mutter: Window.shade
      - name: _NET_WM_ACTION_STICK
        sway: sticky
        mutter: Window.stick
      - name: _NET_WM_ACTION_MAXIMIZE_HORZ
        mutter: xdg-shell / Window.maximize^5
        kws: xdg-shell / KDE plasma-window-management^1^5
        wlr: xdg-shell / wlr-foreign-toplevel-management^1^3^5
        mir: xdg-shell^5
        e: xdg-shell / org.enlightenment.wm.Window.{M|Unm}aximize^3^5
      - name: _NET_WM_ACTION_MAXIMIZE_VERT
        mutter: xdg-shell / Window.maximize^5
        kws: xdg-shell / KDE plasma-window-management^1^5
        wlr: xdg-shell / wlr-foreign-toplevel-management^1^3^5
        mir: xdg-shell^5
        e: xdg-shell / org.enlightenment.wm.Window.{M|Unm}aximize^3^5
      - name: _NET_WM_ACTION_FULLSCREEN
        mutter: xdg-shell / Window.make_fullscreen^5
        kws: xdg-shell / KDE plasma-window-management^1^5
        wlr: xdg-shell / wlr-foreign-toplevel-management^1^3^5
        mir: xdg-shell^5
        e: xdg-shell^5
        sway: fullscreen
      - name: _NET_WM_ACTION_CHANGE_DESKTOP
        e: org.enlightenment.wm.Window.SendToDesktop
      - name: _NET_WM_ACTION_CLOSE
        mutter: xdg-shell^5
        kws: xdg-shell / KDE plasma-window-management^1^5
        wlr: xdg-shell / wlr-foreign-toplevel-management^1^5
        mir: xdg-shell^5
        e: xdg-shell^5
      - name: _NET_WM_ACTION_ABOVE
        mutter: xdg-shell / Window.make_above^5
        kws: xdg-shell / KDE plasma-shell / KDE plasma-window-management^1^5^11
        wlr: xdg-shell / wlr-layer-shell ^5
        mir: xdg-shell^5
        e: xdg-shell^5
      - name: _NET_WM_ACTION_BELOW
        wlr: wlr-layer-shell^5
        kws: KDE plasma-shell / KDE plasma-window-management^1^11
  - group: XKB
    feats:
      - name: XkbLockGroup
        mutter: "?"
        kws: "?"
        wlr: "?"
        mir: "?"
        e: "?"
  - group: Selections
    feats:
    - name: PRIMARY
    - name: SECONDARY
    - name: CLIPBOARD
    - name: ConvertSelection
    - name: Managers
      wlr: wlr-data-control
  - group: XF86VIDMODE
    feats:
    - name: ModeLine
      usage: games with strict resolution modes
      kws: KDE output-management / KDE outputdevice^21
    - name: Gamma
      usage: xbrightness, xgamma, redshift
      wlr: wlr-gamma-control
      kws: KDE output-management
  - group: Grabbing
    feats:
    - name: Pointer
      usage: games
    - name: Button
    - name: Keyboard
      usage: games, screen lockers, password prompts
      mutter: xwayland-keyboard-grab
      wlr: wlr-input-inhibitor, wlr-layer-shell^4^5
    - name: Key
      usage: global hotkeys
      kws: KDE keystate^10
      sway: bindsym
  - group: Queries
    feats:
    - name: Tree
    - name: Pointer
      usage: oneko
    - name: Keymap
    - name: Font
    - name: TextExtents
    - name: Colors
    - name: BestSize
    - name: Extension
  - group: Get
    feats:
    - name: Geometry
      mutter: /org/gnome/shell/Introspect / Window.get_frame_rect^17^18^19^20
      kws: KDE plasma-window-management^1^19^20
      sway: GET_TREE^19
  - group: XTEST
    feats:
    - name: GetVersion
    - name: CompareCursor
    - name: FakeInput
      usage: xdotool, showkey
      any: libinput^15
      wlr: virtual-keyboard / wlr-virtual-pointer / libinput ^15
      kws: KDE fake input / libinput^15
    - name: GrabControl
  - group: XEMBED
    feats:
    - name: ReparentWindow
      usage: tray, gtk_socket plugin for Double Commander, xfce4-panel applets, DAW plugins
      any: SNI / wl_subcompositor^5^12
    - name: EMBEDDED_NOTIFY
      any: StatusNotifierHostRegistered^12^13
    - name: Window activation
    - name: Focus
    - name: Modality
    - name: Accelerators
  - group: System tray
    feats:
    - name: REQUEST_DOCK
      usage: tray icons embedding
      any: StatusNotifierItemRegistered
      arcan: StatusNotifierItemRegistered / SEGID_ICON
    - name: MESSAGE
      usage: balloon tooltips from tray icons
      any: org.freedesktop.Notifications^14
  - group: Miscellanous
    feats:
    - name: WM crash persistence
      mutter: "-"
      e: Session Recovery Extension^2
      arcan: SHMIF
      kwin: wl_display_reconnect^2
    - name: WM decorations
      mutter: "-"
      kws: server-decoration
      wlr: server-decoration
    - name: XShm (screen capture)
      usage: screen shooters/capturers, color pickers, screen sharing
      mutter: PipeWire, portals
      kws: KDE screencast (a PipeWire wrapper)
      wlr: wlr-export-dmabuf / wlr-screencopy
    - name: Xinerama
      wlr: wlr-output-management
      kws: KDE outputdevice
    - name: DPMS
      wlr: wlr-output-power-management^7
      kws: KDE DPMS

footnotes:
  - wlr-foreign-toplevel-management and plasma-window-management support only one client at time. Wanna a compositor-independent taskbar and something like Devilspie simultaneously? fail. # 1
  - Requires client support. # 2
  - xdg-shell, plasma-window-management, wlr-foreign-toplevel-management and org.enlightenment.wm.Window.{M|Unm}aximize can't separately maximize horizontally or vertically. # 3
  - wlr-input-inhibitor provides screen locker functionality only (grab prevention), no complete grabbing # 4
  - wl_subcompositor, xdg-shell and layer-shell provide access only to own surfaces, or those explicitly obtained via xdg-foreign. # 5
  - gnome-shell Window.move[_resize]_frame, xdg-shell and layer-shell provide an agnostic approach that masks the actual output size with anchors. # 6
  - wlr-output-power-management provides only on/off modes. # 7
  - REDACTED # 8
  - xdg-activation is constrained by explicit client-to-client IPC. # 9
  - KDE keystate is limited to lock keys. # 10
  - KDE plasma-shell is limited to manipulating own surfaces and can be registered only by one client. # 11
  - SNI replaces a very narrow use of XEmbed for tray icons, provided in a declarative way over DBus. Just an icon, a tooltip, a menu of actions and a scroll event, with the appearance implemented completely by a SNI host. No arbitrary actions over a window, like handling a click position, non-square applets (like in Workrave), etc. Doesn't really depend on Wayland compositors, as they don't interfere with the possibility of other apps to become SNI hosts, but the compositors may implement a SNI host themselves. # 12
  - StatusNotifierHostRegistered is a rough replacement, as every certain item can't know if it is drawn by the host, just that the host exists. # 13
  - Freedesktop Notifications roughly replace balloon messages, as they can in no way be associated with a certain tray icon. To be honest, balloons were scarcely supported by X systray implementations too. # 14
  - "libinput requires either to add the user to the libinput group or to run the client from root: both are even less secure then the X.Org approach. Also, it works on a low level and doesn't actually have anything to do with Wayland, so things akin to XTestCompareCursorWithWindow and so wouldn't work." # 15
  - Sway's kill command applies only to a currently focused window. # 16
  - /org/gnome/shell/Introspect is disabled by default in gsettings; read-only access. # 17
  - /org/gnome/shell/Introspect provides the width/height only. # 18
  - Window.get_frame_rect, plasma-window-management and GET_TREE don't provide the bit depth of a surface. # 19
  - Window.get_frame_rect, plasma-window-management doesn't provide the border width of a surface. # 20
  - KDE output management doesn't handle HSync/VSync, though does handle VRR. # 21
  - Read-only access. # 22
  - Write-only access. # 23
  - Window-agnostic information. # 24
  - gnome-shell Window cannot be prohibited from becoming sticky, fullscreen, changing the desktop, going above/below, and from maximizing only horizontally or only vertically. # 25
